##**ML Project - Credit Card Fraud Detection**

In [189]:
# First, we'll import Pandas, Numpy a data processing and CSV file I/O library
import pandas as pd
import numpy as np

# We'll also import seaborn, a Python graphing library
import warnings # current version of seaborn generates a bunch of warnings that we'll ignore
warnings.filterwarnings("ignore")
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="white", color_codes=True)

In [190]:
# Next, we'll load the dataset, which is in the "../input/" directory
df = pd.read_csv('/content/creditcard.csv') # the dataset is now a Pandas DataFrame

# Let's see what's in the data - Jupyter notebooks print the result of the last thing you do
df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [191]:
credit_card_data.tail()

Time        V1        V2  ...       V28  Amount  Class
279186  168697.0 -1.448540 -0.106524  ...  0.166265  157.00    0.0
279187  168698.0 -1.698935  1.318773  ... -0.224998   74.90    0.0
279188  168698.0 -1.698935  1.318773  ... -0.224998   74.90    0.0
279189  168698.0 -1.752086  1.235061  ... -0.204416   32.48    0.0
279190  168698.0 -1.752086  1.235061  ...       NaN     NaN    NaN

[5 rows x 31 columns]

## Perform data cleanup as required

In [192]:
credit_card_data.shape

(279191, 31)

In [193]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279191 entries, 0 to 279190
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    279191 non-null  float64
 1   V1      279191 non-null  float64
 2   V2      279191 non-null  float64
 3   V3      279191 non-null  float64
 4   V4      279191 non-null  float64
 5   V5      279191 non-null  float64
 6   V6      279190 non-null  float64
 7   V7      279190 non-null  float64
 8   V8      279190 non-null  float64
 9   V9      279190 non-null  float64
 10  V10     279190 non-null  float64
 11  V11     279190 non-null  float64
 12  V12     279190 non-null  float64
 13  V13     279190 non-null  float64
 14  V14     279190 non-null  float64
 15  V15     279190 non-null  float64
 16  V16     279190 non-null  float64
 17  V17     279190 non-null  float64
 18  V18     279190 non-null  float64
 19  V19     279190 non-null  float64
 20  V20     279190 non-null  float64
 21  V21     27

In [194]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    278703
1.0       487
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [195]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [196]:
print(legit.shape)
print(fraud.shape)

(278703, 31)
(487, 31)


In [197]:
# statistical measures of the data
legit.Amount.describe()

count    278703.000000
mean         88.676558
std         250.460854
min           0.000000
25%           5.760000
50%          22.190000
75%          77.850000
max       25691.160000
Name: Amount, dtype: float64

In [198]:
fraud.Amount.describe()

count     487.000000
mean      121.913326
std       257.561705
min         0.000000
25%         1.000000
50%         9.130000
75%       105.350000
max      2125.870000
Name: Amount, dtype: float64

In [199]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

Time        V1        V2  ...       V27       V28      Amount
Class                                    ...                                
0.0    93312.148890  0.007147 -0.013057  ... -0.000292 -0.000088   88.676558
1.0    79834.240246 -4.816122  3.652183  ...  0.168312  0.075910  121.913326

[2 rows x 30 columns]

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 487

In [200]:
legit_sample = legit.sample(n=487)

Concatenating two DataFrames

In [201]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [202]:
new_dataset.head()

Time        V1        V2  ...       V28  Amount  Class
237724  149366.0  2.105345 -0.131673  ... -0.073748    1.98    0.0
65052    51411.0 -1.214709  1.414825  ... -0.005792    0.92    0.0
70497    53892.0  0.545471 -0.623443  ...  0.075521  348.00    0.0
62546    50311.0 -4.385687 -2.135949  ...  0.547172  552.35    0.0
271920  164811.0 -0.632350 -0.246712  ...  0.160334   59.90    0.0

[5 rows x 31 columns]

In [203]:
new_dataset.tail()

Time        V1        V2  ...       V28  Amount  Class
274382  165981.0 -5.766879 -8.402154  ...  0.583799    0.00    1.0
274475  166028.0 -0.956390  2.361594  ...  0.443299   39.90    1.0
275992  166831.0 -2.027135 -1.131890  ... -0.091646  634.30    1.0
276071  166883.0  2.091900 -0.757459  ... -0.015470   19.95    1.0
276864  167338.0 -1.374424  2.793185  ...  0.096711  349.08    1.0

[5 rows x 31 columns]

In [204]:
new_dataset['Class'].value_counts()

1.0    487
0.0    487
Name: Class, dtype: int64

In [205]:
new_dataset.groupby('Class').mean()

Time        V1        V2  ...       V27       V28      Amount
Class                                    ...                                
0.0    94319.127310 -0.053513  0.063105  ... -0.007270 -0.000727   87.269363
1.0    79834.240246 -4.816122  3.652183  ...  0.168312  0.075910  121.913326

[2 rows x 30 columns]

## Data Preparation: feature engineering

In [206]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [207]:
print(X)

            Time        V1        V2  ...       V27       V28  Amount
237724  149366.0  2.105345 -0.131673  ... -0.080313 -0.073748    1.98
65052    51411.0 -1.214709  1.414825  ...  0.058543 -0.005792    0.92
70497    53892.0  0.545471 -0.623443  ... -0.040073  0.075521  348.00
62546    50311.0 -4.385687 -2.135949  ...  0.950145  0.547172  552.35
271920  164811.0 -0.632350 -0.246712  ...  0.117492  0.160334   59.90
...          ...       ...       ...  ...       ...       ...     ...
274382  165981.0 -5.766879 -8.402154  ...  0.073269  0.583799    0.00
274475  166028.0 -0.956390  2.361594  ...  0.683535  0.443299   39.90
275992  166831.0 -2.027135 -1.131890  ...  0.508712 -0.091646  634.30
276071  166883.0  2.091900 -0.757459  ...  0.020182 -0.015470   19.95
276864  167338.0 -1.374424  2.793185  ...  0.454982  0.096711  349.08

[974 rows x 30 columns]


In [208]:
print(Y)

237724    0.0
65052     0.0
70497     0.0
62546     0.0
271920    0.0
         ... 
274382    1.0
274475    1.0
275992    1.0
276071    1.0
276864    1.0
Name: Class, Length: 974, dtype: float64


In [209]:
# split into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [210]:
print(X.shape, X_train.shape, X_test.shape)

(974, 30) (779, 30) (195, 30)


## Model Training

Since our dependent variable is a Binary classification type so we can use Logistic Regression or k-Nearest Neighbors, Decision Trees, Support Vector Machine, Naive Bayes.

In [211]:
# Model with all features
from sklearn.linear_model import LogisticRegression

# training the Logistic Regression Model with Training Data
model=LogisticRegression()
model.fit(X_train, Y_train)

X_train_prediction = model.predict(X_train)

In [212]:
# Logistic Regression (LR)
# for Logistic Regression algorithm
# Training
from sklearn.linear_model import LogisticRegression
classifierLR = LogisticRegression()
classifierLR.fit(X_train,Y_train)
y_pred_train= classifierLR.predict(X_train)

# Evaluating the Algorithm on training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_train, y_pred_train))  
print(classification_report(Y_train, y_pred_train))
print(accuracy_score(Y_train,y_pred_train))

[[377  12]
 [ 32 358]]
              precision    recall  f1-score   support

         0.0       0.92      0.97      0.94       389
         1.0       0.97      0.92      0.94       390

    accuracy                           0.94       779
   macro avg       0.94      0.94      0.94       779
weighted avg       0.94      0.94      0.94       779

0.9435173299101413


In [213]:
# Logistic Regression (LR)
# for Logistic Regression algorithm
# Training
from sklearn.linear_model import LogisticRegression
classifierLR = LogisticRegression()
classifierLR.fit(X_train,Y_train)
y_pred_test= classifierLR.predict(X_test)

# Evaluating the Algorithm on test data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_test, y_pred_test))  
print(classification_report(Y_test, y_pred_test))
print(accuracy_score(Y_test,y_pred_test))

[[92  6]
 [ 8 89]]
              precision    recall  f1-score   support

         0.0       0.92      0.94      0.93        98
         1.0       0.94      0.92      0.93        97

    accuracy                           0.93       195
   macro avg       0.93      0.93      0.93       195
weighted avg       0.93      0.93      0.93       195

0.9282051282051282


In [214]:
# Decision Tree
#for using Decision Tree Algoithm
# Training
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier()
classifierDT.fit(X_train,Y_train)
y_pred_train1= classifierDT.predict(X_train)

# Evaluating the Algorithm on training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_train, y_pred_train1))  
print(classification_report(Y_train, y_pred_train1))
print(accuracy_score(Y_train,y_pred_train1))

[[389   0]
 [  0 390]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       389
         1.0       1.00      1.00      1.00       390

    accuracy                           1.00       779
   macro avg       1.00      1.00      1.00       779
weighted avg       1.00      1.00      1.00       779

1.0


In [215]:
# Decision Tree
#for using Decision Tree Algoithm
# Training
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier()
classifierDT.fit(X_train,Y_train)
y_pred_test1= classifierDT.predict(X_test)

# Evaluating the Algorithm on test data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_test, y_pred_test1))  
print(classification_report(Y_test, y_pred_test1))
print(accuracy_score(Y_test,y_pred_test1))

[[90  8]
 [10 87]]
              precision    recall  f1-score   support

         0.0       0.90      0.92      0.91        98
         1.0       0.92      0.90      0.91        97

    accuracy                           0.91       195
   macro avg       0.91      0.91      0.91       195
weighted avg       0.91      0.91      0.91       195

0.9076923076923077


In [216]:
# Support Vector Machine (SVM)
#for Support Vector Machine (SVM) Algorithm
# Training
from sklearn import svm
classifierSVM = svm.SVC()
classifierSVM.fit(X_train,Y_train)
y_pred_train2 = classifierSVM.predict(X_train)

# Evaluating the Algorithm on training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_train, y_pred_train2))  
print(classification_report(Y_train, y_pred_train2))
print(accuracy_score(Y_train,y_pred_train2))

[[201 188]
 [179 211]]
              precision    recall  f1-score   support

         0.0       0.53      0.52      0.52       389
         1.0       0.53      0.54      0.53       390

    accuracy                           0.53       779
   macro avg       0.53      0.53      0.53       779
weighted avg       0.53      0.53      0.53       779

0.5288831835686778


In [217]:
# Support Vector Machine (SVM)
#for Support Vector Machine (SVM) Algorithm
# Training
from sklearn import svm
classifierSVM = svm.SVC()
classifierSVM.fit(X_train,Y_train)
y_pred_test2= classifierSVM.predict(X_test)

# Evaluating the Algorithm on test data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_test, y_pred_test2))  
print(classification_report(Y_test, y_pred_test2))
print(accuracy_score(Y_test,y_pred_test2))

[[52 46]
 [44 53]]
              precision    recall  f1-score   support

         0.0       0.54      0.53      0.54        98
         1.0       0.54      0.55      0.54        97

    accuracy                           0.54       195
   macro avg       0.54      0.54      0.54       195
weighted avg       0.54      0.54      0.54       195

0.5384615384615384


In [218]:
# K-Nearest Neighbors (KNN)
#for using K-Nearest Neighbors Algoithm
# Training
from sklearn.neighbors import KNeighborsClassifier
classifierKNN = KNeighborsClassifier(n_neighbors=5)
classifierKNN.fit(X_train,Y_train)
y_pred_train3 = classifierKNN.predict(X_train)

# Evaluating the Algorithm on training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_train, y_pred_train3))  
print(classification_report(Y_train, y_pred_train3))
print(accuracy_score(Y_train,y_pred_train3))

[[302  87]
 [106 284]]
              precision    recall  f1-score   support

         0.0       0.74      0.78      0.76       389
         1.0       0.77      0.73      0.75       390

    accuracy                           0.75       779
   macro avg       0.75      0.75      0.75       779
weighted avg       0.75      0.75      0.75       779

0.7522464698331194


In [219]:
# K-Nearest Neighbors (KNN)
#for using K-Nearest Neighbors Algoithm
# Training
from sklearn.neighbors import KNeighborsClassifier
classifierKNN = KNeighborsClassifier(n_neighbors=5)
classifierKNN.fit(X_train,Y_train)
y_pred_test3= classifierKNN.predict(X_test)

# Evaluating the Algorithm on test data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  
print(confusion_matrix(Y_test, y_pred_test3))  
print(classification_report(Y_test, y_pred_test3))
print(accuracy_score(Y_test,y_pred_test3))

[[55 43]
 [39 58]]
              precision    recall  f1-score   support

         0.0       0.59      0.56      0.57        98
         1.0       0.57      0.60      0.59        97

    accuracy                           0.58       195
   macro avg       0.58      0.58      0.58       195
weighted avg       0.58      0.58      0.58       195

0.5794871794871795
